sudo: required

services:
  - docker

before_install:
  - docker build -t mouradevsoltani/docker-react -f Dockerfile.dev .

script:
  - docker run mouradevsoltani/docker-react npm run test -- --coverage